### PR TITLE
hffix_fields.hpp: Use X macros to simplify and add msg_type enum

### PR DESCRIPTION
**Pull request by chris-pattern**

### CODE REVIEW

**Comment by chris-pattern** [comment]
oh i just read the comment that says to use the haskell script to regenerate.  oof.
in any case, using X macros will make it much easier for people to expand in the future.

**Comment by jamesdbrock** [comment]
Thanks for the PR! I can't look at this right now; will look in a few weeks.

**Comment by jamesdbrock** [comment]
I appreciate the PR, but I don't really think that this PR is better. We don't want to enter all the FIX fields by hand, we want to auto-generate the C++ FIX field code from the `Fields.xml` file.

Further, we do want to make some manual adjustments to the generated code, and we can do that in the script, for example:

https://github.com/jamesdbrock/hffix/blob/8712946a02aedaf339b640e02d279bdeaadbf630/fixspec/spec-parse-fields/src/Main.hs#L60-L76

But I confess that figuring out how to adjust the generated code could be easier.

What adjustments to the generated `hffix_fields.hpp` file did you want to make? If you found some problems in the generated `hffix_fields.hpp` file and you want to fix them, then I'd like to do that.

**Comment by jamesdbrock** [comment]
So this is what you think the definitions should look like (with the X macro `HFFIX_FIX_MSGTYPE`)?

```C++
namespace msg_type {
#if __cplusplus >= 201103L
#define HFFIX_dummy(name, value) static constexpr const char* const name = value;
#else
#define HFFIX_dummy(name, value) static const char* const name = value;
#endif
HFFIX_FIX_MSGTYPE(HFFIX_dummy)
#undef HFFIX_dummy
} // namespace msg_type
```

This looks good to me.

**Comment by chris-pattern** [comment]
Cool!

**Comment by jamesdbrock** [comment]
> you don't support tag 1362 https://www.onixs.biz/fix-dictionary/5.0.sp2/tagnum_1362.html 

Remember that you can always just use the tag number `1362` because tags are `int`s in *hffix*.

You can name the tag if you want

```c++
const int nofills = 1362;
```

You can add also add it to your field dictionary
```c++
std::map<int, std::string> fields;
hffix::dictionary_init_field(fields);
fields[1362] = "NoFills";
```

**Pull request closed without merging**
