### PR TITLE
constrain templates with enable_if, simplify as_int()

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by jamesdbrock** [comment]
This is great but it uses `std::enable_if`, which is C++11. Currently __hffix__ depends only on C++03, which is a feature of this library that I like. We could merge this commit with `#if __cplusplus` fallbacks for C++03, but the fallback for C++03 would be the code which is already there. Which is actually not too crazy because it's an upgrade path to a future in which we deprecate C++03. Let me think about it.

**Comment by arvidn** [comment]
I see. I've also been eyeing ``field_value``; it's almost identical to ``std::string_view`` (which is C++17)

**Comment by jamesdbrock** [comment]
> I've also been eyeing `field_value`; it's almost identical to `std::string_view` (which is C++17)

Yeah it's nice that the committee finally got some [ranges](https://github.com/ericniebler/range-v3) standardized, at least for the special case of strings.

**Comment by jamesdbrock** [comment]
Closing. Not worth the C++11 requirement. Might reopen in the future.

**Pull request closed without merging**
