### PR TITLE
Added few convenience methods.

### PR DESCRIPTION
**Pull request by skuzniar**
Added few convenience methods I found useful while working with string views.

### CODE REVIEW

**Comment by jamesdbrock** [comment]
This PR adds

1. method `message_writer.push_back_header(std::string_view begin_string_version)`.
2. method `messager_writer.push_back_bool(int tag, bool v)` 
3. method `message_reader.as_string_view()`

**Comment by jamesdbrock** [comment]
There is a Boolean type in the spec https://www.fixtrading.org/standards/tagvalue-online/#fix-tagvalue-datatypes which just encodes the characters `'Y'` and `'N'`.

**Comment by jamesdbrock** [comment]
Hi @skuzniar thanks for the PR.

I like the `push_back_header` and `as_string_view` methods. Would you please add a test case for those methods to prove that they work? At the end of this file:

https://github.com/jamesdbrock/hffix/blob/master/test/src/unit_tests.cpp

Let's drop the `push_back_bool` method. For symmetry we should have a `field_value.as_bool()` method, but that method would have to  be designed how to handle the case where the string is neither `'Y'` nor `'N'`. And there isn't one obvious way to do that. So I think it's easier just to let the users write and read one character either `'Y'` or `'N'`.

**Comment by skuzniar** [comment]
Yes, it does not make sense to have push without get. I dropped boolean push and added two tests.

CXXFLAGS="-std=c++1z"  make unit_tests
-e *** Building test/bin/unit_tests ...
c++ -std=c++1z -Wall -Iinclude -o test/bin/unit_tests test/src/unit_tests.cpp
-e *** Built test/bin/unit_tests ...
-e *** Running test/bin/unit_tests ...
test/bin/unit_tests --color_output=true
Running 14 test cases...
BOOST version 1_84

*** No errors detected
-e *** Passed test/bin/unit_tests ...

**Comment by jamesdbrock** [comment]
Thanks!

**Comment by jamesdbrock** [comment]
I published v1.4.0 with your improvements.

**Pull request merged**
