### PR TITLE
Split out the buffer management features of `message_writer`  into a separate class.

### PR DESCRIPTION
**Pull request by dingobye**
This is an excellent open-source project, with rich documentations that are friendly to users.

I would like to make some contributions to this project. I found the TODO list in the README.md, and made some efforts to extract to buffer management feature from `message_writer` class, as shown in this PR.  As a result, it looks more concise when writing new data into the buffer.

### CODE REVIEW

**Comment by jamesdbrock** [comment]
Hi @dingobye thanks for the PR!

It's a pretty big change and I'm not clear about the benefits.

The new `write_buffer` class becomes part of the public API, but `write_buffer` is only used internally by `message_writer`? It seems to me that if `write_buffer` is never meant to be constructed by the user, then it should be part of the undocumented `hffix::details` namespace.

The chaining functions, on the plus side, add some static correctness guarantee that the `next_` pointer will be incremented by the correct amount. The thing is, the `next_` pointer is only incremented by internal methods, so no library users will benefit from the extra correctness guarantee.

On the minus side, the chaining functions add a layer of indirection so that it is more difficult for library authors to verify correctness by inspection, on the rare occasions when someone is debugging one of these functions or adding a new one.

The `write_buffer` has private `begin_`, `end_` and `pos_` members which mirror and duplicate the `message_writer` private `begin_`, `end_` and `next_` members. This also seems to me to be an unnecessary indirection. The `write_buffer` chaining functions could just be methods of `message_writer`.

I'm very grateful to you for taking the time to try to improve __hffix__, but I'm inclined to pass on your PR. Did I miss anything? What is your reasoning behind wanting to add the `write_buffer` class?

**Comment by dingobye** [comment]
Thank you for the feedback, James!

The motivation is from a TODO task [here](https://github.com/jamesdbrock/hffix/blob/master/README.md#todo), which says "_Split out the buffer-management features of message_reader and message_writer into separate classes_". Adding the `write_buffer` class can separate the buffer management logics (i.e., maintaining `begin_`, `end_`, `next_`), thus that `message_writer` is more focused on processing FIX messages. It should have been placed in `hffix::details` namespace though.

Looks like I got the wrong idea about the TODO task. Would you share some more details on this, please?

**Comment by jamesdbrock** [comment]
Hi @dingobye , I wrote out some thoughts about this in issue #26. 

I'm not sure exactly what code should be written to improve the buffer management, but I'm open to suggestions.

**Comment by jamesdbrock** [comment]
I'm closing this PR for now, but will be willing to reopen it later for more consideration.

**Pull request closed without merging**
