### PR TITLE
Support for floating point using C++20.

### PR DESCRIPTION
**Pull request by hlmodi**
I know this may not be the most secure thing in the world, but...

### CODE REVIEW

**Comment by jamesdbrock** [comment]
If by “floating point” you mean [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754), then no, I don’t think support for that is a good idea, because there is no way to do it correctly.

The problem is that most fractional prices, like for example *$1.01*, cannot be represented in IEEE 754. So what kind of rounding approximation strategy should the **hffix** library use for these fractional prices? I think the best answer is that the **hffix** library doesn’t support this at all. If the library user wants to use IEEE 754 price representation, then the user can choose their own rounding approximation.

I don’t recommend using IEEE 754 for prices at all, I recommend using some kind of [fixed-point numeric library](https://github.com/has-castle/fixed_point).

**Comment by jamesdbrock** [comment]
This PR proposes adding a function

```c++
void push_back_floating(int tag, std::floating_point auto number)
```

which serializes by

```c++
std::format_to(next_, "{}", number);
```

If you want to serialize floating point numbers in this way then you can just `std::format_to` your number to a string and then `hffix::push_back_string`.

**Comment by hlmodi** [comment]
Agreed. It's clear that my initial suggestion may not have been the most sound idea to begin with...

(by the way, do you have an opinion on https://github.com/OleksandrKvl/sbepp vs https://github.com/real-logic/simple-binary-encoding)

Thanks!

**Comment by jamesdbrock** [comment]
> do you have an opinion on https://github.com/OleksandrKvl/sbepp vs https://github.com/real-logic/simple-binary-encoding

I don't have an opinion.

Thanks for the PR, even though we're not going to merge this.

**Pull request closed without merging**
