### PR TITLE
hffix_fields: fix typo in tag 267 name (NoMDEntryTypes)

### PR DESCRIPTION
**Pull request by msherman13**

### CODE REVIEW

**Comment by jamesdbrock** [comment]
So the thing about this is that those strange spellings are in the official spec from the FIX protocol organization `fixspec/fix.4.4/FIXML4.4v20030618.dtd`.

This file, `hffix_fields.hpp` is generated by reading those spec documents. See the comment at the top of the file for details.

**Comment by msherman13** [comment]
OK fair enough. I was going off of https://www.onixs.biz/fix-dictionary which I guess didn't adhere to the spec.

**Comment by jvirtanen** [comment]
It seems that these are not actually typos but the _abbreviated names_ for the fields. See the definitions in the [FIX Repository](https://www.fixtrading.org/standards/fix-repository/):
```xml
<Field added="FIX.4.2">
    <Tag>267</Tag>
    <Name>NoMDEntryTypes</Name>
    <Type>NumInGroup</Type>
    <AbbrName>NoMDEntryTyps</AbbrName>
    <NotReqXML>0</NotReqXML>
    <Description>Number of MDEntryType (269) fields requested.</Description>
</Field>
```
I'm not very familiar with FIXML but it seems odd that it would use the abbreviated name just for these two fields. If it was consistent, it would call, for example, MDEntryPx(270) "Px" as well:
```xml
<Field added="FIX.4.2">
    <Tag>270</Tag>
    <Name>MDEntryPx</Name>
    <Type>Price</Type>
    <AbbrName>Px</AbbrName>
    <NotReqXML>0</NotReqXML>
    <Description>Price of the Market Data Entry.</Description>
</Field>
```
I'm myself using the `<Name>` elements in the FIX Repository to generate the tags for the standard protocol versions in [Philadelphia](https://github.com/paritytrading/philadelphia).

**Comment by jamesdbrock** [comment]
@jvirtanen Yeah, that's what's going on. *hffix* should probably use __FIX Repository__ rather than parse the original protocol spec documents.

**Comment by jamesdbrock** [comment]
Thanks @msherman13 for submitting this pull request, even though you closed it. The conversation you started is causing me to write up a parser for the __FIX Repository__.

**Comment by jamesdbrock** [comment]
@msherman13 This branch will solve the abbreviated field names problem. https://github.com/jamesdbrock/hffix/pull/18

**Pull request closed without merging**
